/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
  }),
);

export const testimonials = sqliteTable(
  "testimonials",
  {
    id: integer("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    punchline: text("punchline").notNull(),
    fullTestimonial: text("full_testimonial", { mode: "json" }).notNull(),
    whoDunnit: text("who_dunnit").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    testimonials_image_idx: index("testimonials_image_idx").on(columns.image),
    testimonials_updated_at_idx: index("testimonials_updated_at_idx").on(
      columns.updatedAt,
    ),
    testimonials_created_at_idx: index("testimonials_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const announcements = sqliteTable(
  "announcements",
  {
    id: integer("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    title: text("title").notNull(),
    content: text("content", { mode: "json" }).notNull(),
    publishedAt: text("published_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    publishedBy: text("published_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    announcements_image_idx: index("announcements_image_idx").on(columns.image),
    announcements_published_by_idx: index("announcements_published_by_idx").on(
      columns.publishedBy,
    ),
    announcements_updated_at_idx: index("announcements_updated_at_idx").on(
      columns.updatedAt,
    ),
    announcements_created_at_idx: index("announcements_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const faq_categories = sqliteTable(
  "faq_categories",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    colorPalette: text("color_palette", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    faq_categories_updated_at_idx: index("faq_categories_updated_at_idx").on(
      columns.updatedAt,
    ),
    faq_categories_created_at_idx: index("faq_categories_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const faq_questions = sqliteTable(
  "faq_questions",
  {
    id: integer("id").primaryKey(),
    category: integer("category_id")
      .notNull()
      .references(() => faq_categories.id, {
        onDelete: "set null",
      }),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    faq_questions_category_idx: index("faq_questions_category_idx").on(
      columns.category,
    ),
    faq_questions_updated_at_idx: index("faq_questions_updated_at_idx").on(
      columns.updatedAt,
    ),
    faq_questions_created_at_idx: index("faq_questions_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const users_accounts = sqliteTable(
  "users_accounts",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    type: text("type").notNull(),
  },
  (columns) => ({
    _orderIdx: index("users_accounts_order_idx").on(columns._order),
    _parentIDIdx: index("users_accounts_parent_id_idx").on(columns._parentID),
    users_accounts_provider_account_id_idx: index(
      "users_accounts_provider_account_id_idx",
    ).on(columns.providerAccountId),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_accounts_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    emailVerified: text("email_verified").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    name: text("name"),
    image: text("image"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
  }),
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    mediaID: integer("media_id"),
    testimonialsID: integer("testimonials_id"),
    announcementsID: integer("announcements_id"),
    faqCategoriesID: integer("faq_categories_id"),
    faqQuestionsID: integer("faq_questions_id"),
    usersID: text("users_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx",
    ).on(columns.mediaID),
    payload_locked_documents_rels_testimonials_id_idx: index(
      "payload_locked_documents_rels_testimonials_id_idx",
    ).on(columns.testimonialsID),
    payload_locked_documents_rels_announcements_id_idx: index(
      "payload_locked_documents_rels_announcements_id_idx",
    ).on(columns.announcementsID),
    payload_locked_documents_rels_faq_categories_id_idx: index(
      "payload_locked_documents_rels_faq_categories_id_idx",
    ).on(columns.faqCategoriesID),
    payload_locked_documents_rels_faq_questions_id_idx: index(
      "payload_locked_documents_rels_faq_questions_id_idx",
    ).on(columns.faqQuestionsID),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    testimonialsIdFk: foreignKey({
      columns: [columns["testimonialsID"]],
      foreignColumns: [testimonials.id],
      name: "payload_locked_documents_rels_testimonials_fk",
    }).onDelete("cascade"),
    announcementsIdFk: foreignKey({
      columns: [columns["announcementsID"]],
      foreignColumns: [announcements.id],
      name: "payload_locked_documents_rels_announcements_fk",
    }).onDelete("cascade"),
    faqCategoriesIdFk: foreignKey({
      columns: [columns["faqCategoriesID"]],
      foreignColumns: [faq_categories.id],
      name: "payload_locked_documents_rels_faq_categories_fk",
    }).onDelete("cascade"),
    faqQuestionsIdFk: foreignKey({
      columns: [columns["faqQuestionsID"]],
      foreignColumns: [faq_questions.id],
      name: "payload_locked_documents_rels_faq_questions_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: text("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const nav_blocks_link_item = sqliteTable(
  "nav_blocks_link_item",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    displayText: text("display_text").notNull(),
    targetLink: text("target_link").notNull(),
    displayIcon: text("display_icon", {
      enum: [
        "About the Regulations",
        "About the WCA",
        "Admin Results",
        "All Competitions",
        "Bookmark",
        "Clone",
        "Competition Not Started",
        "Registration Closed",
        "Registration Closed (Red)",
        "Registration Full but Open",
        "Registration Full but Open (Orange)",
        "Registration Not Full, Open",
        "Registration Not Full, Open (Green)",
        "Registration Not Open Yet",
        "Registration Not Open Yet (Grey)",
        "Registration Open Date",
        "Registration Close Date",
        "Competitors",
        "Contact",
        "Delegate Report",
        "Details",
        "Developer Export",
        "Disciplinary Log",
        "Disclaimer",
        "Download",
        "Edit",
        "Educational Resources",
        "Error",
        "External Link",
        "Facebook",
        "Filters",
        "GitHub",
        "Guidelines",
        "Help and FAQs",
        "Incidents Log",
        "Information",
        "Instagram",
        "Language",
        "List",
        "Location",
        "Manage Tabs",
        "Map",
        "Media Submission",
        "Menu",
        "Multimedia",
        "My Competitions",
        "My Results",
        "National Championship",
        "New Competition",
        "On-the-Spot Registration",
        "Payment",
        "Privacy",
        "Rankings",
        "Records",
        "Regional Organisations",
        "Register",
        "Registration",
        "Regulations and Guidelines",
        "Regulations History",
        "Regulations",
        "Results Export",
        "Scrambles",
        "Search",
        "Spectators",
        "Speedcubing History",
        "Spots Left",
        "Statistics",
        "Teams, Committees and Councils",
        "Tools",
        "Translators",
        "Twitch",
        "User",
        "Users / Persons",
        "Venue",
        "WCA Delegates",
        "WCA Documents",
        "WCA Live",
        "WCA Officers and Board",
        "Weibo",
        "X (formerly Twitter)",
        "YouTube",
      ],
    }),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("nav_blocks_link_item_order_idx").on(columns._order),
    _parentIDIdx: index("nav_blocks_link_item_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("nav_blocks_link_item_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [nav.id],
      name: "nav_blocks_link_item_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const nav_blocks_nested_dropdown = sqliteTable(
  "nav_blocks_nested_dropdown",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    displayIcon: text("display_icon", {
      enum: [
        "About the Regulations",
        "About the WCA",
        "Admin Results",
        "All Competitions",
        "Bookmark",
        "Clone",
        "Competition Not Started",
        "Registration Closed",
        "Registration Closed (Red)",
        "Registration Full but Open",
        "Registration Full but Open (Orange)",
        "Registration Not Full, Open",
        "Registration Not Full, Open (Green)",
        "Registration Not Open Yet",
        "Registration Not Open Yet (Grey)",
        "Registration Open Date",
        "Registration Close Date",
        "Competitors",
        "Contact",
        "Delegate Report",
        "Details",
        "Developer Export",
        "Disciplinary Log",
        "Disclaimer",
        "Download",
        "Edit",
        "Educational Resources",
        "Error",
        "External Link",
        "Facebook",
        "Filters",
        "GitHub",
        "Guidelines",
        "Help and FAQs",
        "Incidents Log",
        "Information",
        "Instagram",
        "Language",
        "List",
        "Location",
        "Manage Tabs",
        "Map",
        "Media Submission",
        "Menu",
        "Multimedia",
        "My Competitions",
        "My Results",
        "National Championship",
        "New Competition",
        "On-the-Spot Registration",
        "Payment",
        "Privacy",
        "Rankings",
        "Records",
        "Regional Organisations",
        "Register",
        "Registration",
        "Regulations and Guidelines",
        "Regulations History",
        "Regulations",
        "Results Export",
        "Scrambles",
        "Search",
        "Spectators",
        "Speedcubing History",
        "Spots Left",
        "Statistics",
        "Teams, Committees and Councils",
        "Tools",
        "Translators",
        "Twitch",
        "User",
        "Users / Persons",
        "Venue",
        "WCA Delegates",
        "WCA Documents",
        "WCA Live",
        "WCA Officers and Board",
        "Weibo",
        "X (formerly Twitter)",
        "YouTube",
      ],
    }),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("nav_blocks_nested_dropdown_order_idx").on(columns._order),
    _parentIDIdx: index("nav_blocks_nested_dropdown_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("nav_blocks_nested_dropdown_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [nav.id],
      name: "nav_blocks_nested_dropdown_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const nav_blocks_visual_divider = sqliteTable(
  "nav_blocks_visual_divider",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("nav_blocks_visual_divider_order_idx").on(columns._order),
    _parentIDIdx: index("nav_blocks_visual_divider_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("nav_blocks_visual_divider_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [nav.id],
      name: "nav_blocks_visual_divider_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const nav_blocks_nav_dropdown = sqliteTable(
  "nav_blocks_nav_dropdown",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    displayIcon: text("display_icon", {
      enum: [
        "About the Regulations",
        "About the WCA",
        "Admin Results",
        "All Competitions",
        "Bookmark",
        "Clone",
        "Competition Not Started",
        "Registration Closed",
        "Registration Closed (Red)",
        "Registration Full but Open",
        "Registration Full but Open (Orange)",
        "Registration Not Full, Open",
        "Registration Not Full, Open (Green)",
        "Registration Not Open Yet",
        "Registration Not Open Yet (Grey)",
        "Registration Open Date",
        "Registration Close Date",
        "Competitors",
        "Contact",
        "Delegate Report",
        "Details",
        "Developer Export",
        "Disciplinary Log",
        "Disclaimer",
        "Download",
        "Edit",
        "Educational Resources",
        "Error",
        "External Link",
        "Facebook",
        "Filters",
        "GitHub",
        "Guidelines",
        "Help and FAQs",
        "Incidents Log",
        "Information",
        "Instagram",
        "Language",
        "List",
        "Location",
        "Manage Tabs",
        "Map",
        "Media Submission",
        "Menu",
        "Multimedia",
        "My Competitions",
        "My Results",
        "National Championship",
        "New Competition",
        "On-the-Spot Registration",
        "Payment",
        "Privacy",
        "Rankings",
        "Records",
        "Regional Organisations",
        "Register",
        "Registration",
        "Regulations and Guidelines",
        "Regulations History",
        "Regulations",
        "Results Export",
        "Scrambles",
        "Search",
        "Spectators",
        "Speedcubing History",
        "Spots Left",
        "Statistics",
        "Teams, Committees and Councils",
        "Tools",
        "Translators",
        "Twitch",
        "User",
        "Users / Persons",
        "Venue",
        "WCA Delegates",
        "WCA Documents",
        "WCA Live",
        "WCA Officers and Board",
        "Weibo",
        "X (formerly Twitter)",
        "YouTube",
      ],
    }),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("nav_blocks_nav_dropdown_order_idx").on(columns._order),
    _parentIDIdx: index("nav_blocks_nav_dropdown_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("nav_blocks_nav_dropdown_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [nav.id],
      name: "nav_blocks_nav_dropdown_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const nav = sqliteTable("nav", {
  id: integer("id").primaryKey(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const home_blocks_text_card = sqliteTable(
  "home_blocks_text_card",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    heading: text("heading").notNull(),
    body: text("body").notNull(),
    variant: text("variant", { enum: ["info", "hero"] })
      .notNull()
      .default("info"),
    separatorAfterHeading: integer("separator_after_heading", {
      mode: "boolean",
    })
      .notNull()
      .default(false),
    buttonText: text("button_text"),
    buttonLink: text("button_link"),
    headerImage: integer("header_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    colorPalette: text("color_palette", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_text_card_order_idx").on(columns._order),
    _parentIDIdx: index("home_blocks_text_card_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_text_card_path_idx").on(columns._path),
    home_blocks_text_card_header_image_idx: index(
      "home_blocks_text_card_header_image_idx",
    ).on(columns.headerImage),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_text_card_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_announcements_section = sqliteTable(
  "home_blocks_announcements_section",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    mainAnnouncement: integer("main_announcement_id")
      .notNull()
      .references(() => announcements.id, {
        onDelete: "set null",
      }),
    colorPalette: text("color_palette", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_announcements_section_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("home_blocks_announcements_section_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_announcements_section_path_idx").on(
      columns._path,
    ),
    home_blocks_announcements_section_main_announcement_idx: index(
      "home_blocks_announcements_section_main_announcement_idx",
    ).on(columns.mainAnnouncement),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_announcements_section_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_image_banner = sqliteTable(
  "home_blocks_image_banner",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    heading: text("heading").notNull(),
    body: text("body").notNull(),
    mainImage: integer("main_image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    colorPalette: text("color_palette", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    bgColor: text("bg_color", {
      enum: [
        "darkBlue",
        "darkRed",
        "darkGreen",
        "darkOrange",
        "darkYellow",
        "blue",
        "red",
        "green",
        "orange",
        "yellow",
        "white",
        "black",
      ],
    }).notNull(),
    headingColor: text("heading_color", {
      enum: [
        "darkBlue",
        "darkRed",
        "darkGreen",
        "darkOrange",
        "darkYellow",
        "blue",
        "red",
        "green",
        "orange",
        "yellow",
        "white",
        "black",
      ],
    }).notNull(),
    textColor: text("text_color", {
      enum: [
        "darkBlue",
        "darkRed",
        "darkGreen",
        "darkOrange",
        "darkYellow",
        "blue",
        "red",
        "green",
        "orange",
        "yellow",
        "white",
        "black",
      ],
    }).notNull(),
    bgImage: integer("bg_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    bgSize: numeric("bg_size").default("100"),
    bgPos: text("bg_pos").default("right"),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_image_banner_order_idx").on(columns._order),
    _parentIDIdx: index("home_blocks_image_banner_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_image_banner_path_idx").on(columns._path),
    home_blocks_image_banner_main_image_idx: index(
      "home_blocks_image_banner_main_image_idx",
    ).on(columns.mainImage),
    home_blocks_image_banner_bg_image_idx: index(
      "home_blocks_image_banner_bg_image_idx",
    ).on(columns.bgImage),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_image_banner_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_image_only_card = sqliteTable(
  "home_blocks_image_only_card",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    mainImage: integer("main_image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    heading: text("heading"),
    colorPalette: text("color_palette", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_image_only_card_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("home_blocks_image_only_card_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_image_only_card_path_idx").on(columns._path),
    home_blocks_image_only_card_main_image_idx: index(
      "home_blocks_image_only_card_main_image_idx",
    ).on(columns.mainImage),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_image_only_card_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_testimonial_slide = sqliteTable(
  "home_blocks_testimonial_slide",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    testimonial: integer("testimonial_id")
      .notNull()
      .references(() => testimonials.id, {
        onDelete: "set null",
      }),
    colorPalette: text("color_palette", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_testimonial_slide_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("home_blocks_testimonial_slide_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_testimonial_slide_path_idx").on(columns._path),
    home_blocks_testimonial_slide_testimonial_idx: index(
      "home_blocks_testimonial_slide_testimonial_idx",
    ).on(columns.testimonial),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_testimonial_slide_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_testimonials_spinner = sqliteTable(
  "home_blocks_testimonials_spinner",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_testimonials_spinner_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("home_blocks_testimonials_spinner_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_testimonials_spinner_path_idx").on(
      columns._path,
    ),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_testimonials_spinner_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_featured_competitions = sqliteTable(
  "home_blocks_featured_competitions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    Competition1ID: text("competition1_i_d").notNull(),
    colorPalette1: text("color_palette1", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    Competition2ID: text("competition2_i_d").notNull(),
    colorPalette2: text("color_palette2", {
      enum: ["blue", "red", "green", "orange", "yellow", "grey"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_featured_competitions_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("home_blocks_featured_competitions_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_featured_competitions_path_idx").on(
      columns._path,
    ),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_featured_competitions_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_two_blocks_leaf = sqliteTable(
  "home_blocks_two_blocks_leaf",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    type: text("type", {
      enum: ["1/3 & 2/3", "2/3 & 1/3", "1/2 & 1/2", "1/4 & 3/4", "3/4 & 1/4"],
    }).notNull(),
    alignment: text("alignment", {
      enum: ["horizontal", "vertical"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_two_blocks_leaf_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("home_blocks_two_blocks_leaf_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_two_blocks_leaf_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_two_blocks_leaf_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_two_blocks_branch = sqliteTable(
  "home_blocks_two_blocks_branch",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    type: text("type", {
      enum: ["1/3 & 2/3", "2/3 & 1/3", "1/2 & 1/2", "1/4 & 3/4", "3/4 & 1/4"],
    }).notNull(),
    alignment: text("alignment", {
      enum: ["horizontal", "vertical"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_two_blocks_branch_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("home_blocks_two_blocks_branch_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_two_blocks_branch_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_two_blocks_branch_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_two_blocks = sqliteTable(
  "home_blocks_two_blocks",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    type: text("type", {
      enum: ["1/3 & 2/3", "2/3 & 1/3", "1/2 & 1/2", "1/4 & 3/4", "3/4 & 1/4"],
    }).notNull(),
    alignment: text("alignment", {
      enum: ["horizontal", "vertical"],
    }).notNull(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_two_blocks_order_idx").on(columns._order),
    _parentIDIdx: index("home_blocks_two_blocks_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_two_blocks_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_two_blocks_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home_blocks_full_width = sqliteTable(
  "home_blocks_full_width",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    blockName: text("block_name"),
  },
  (columns) => ({
    _orderIdx: index("home_blocks_full_width_order_idx").on(columns._order),
    _parentIDIdx: index("home_blocks_full_width_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("home_blocks_full_width_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_blocks_full_width_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const home = sqliteTable("home", {
  id: integer("id").primaryKey(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const home_rels = sqliteTable(
  "home_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    announcementsID: integer("announcements_id"),
  },
  (columns) => ({
    order: index("home_rels_order_idx").on(columns.order),
    parentIdx: index("home_rels_parent_idx").on(columns.parent),
    pathIdx: index("home_rels_path_idx").on(columns.path),
    home_rels_announcements_id_idx: index("home_rels_announcements_id_idx").on(
      columns.announcementsID,
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [home.id],
      name: "home_rels_parent_fk",
    }).onDelete("cascade"),
    announcementsIdFk: foreignKey({
      columns: [columns["announcementsID"]],
      foreignColumns: [announcements.id],
      name: "home_rels_announcements_fk",
    }).onDelete("cascade"),
  }),
);

export const relations_media = relations(media, () => ({}));
export const relations_testimonials = relations(testimonials, ({ one }) => ({
  image: one(media, {
    fields: [testimonials.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_announcements = relations(announcements, ({ one }) => ({
  image: one(media, {
    fields: [announcements.image],
    references: [media.id],
    relationName: "image",
  }),
  publishedBy: one(users, {
    fields: [announcements.publishedBy],
    references: [users.id],
    relationName: "publishedBy",
  }),
}));
export const relations_faq_categories = relations(faq_categories, () => ({}));
export const relations_faq_questions = relations(faq_questions, ({ one }) => ({
  category: one(faq_categories, {
    fields: [faq_questions.category],
    references: [faq_categories.id],
    relationName: "category",
  }),
}));
export const relations_users_accounts = relations(
  users_accounts,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_accounts._parentID],
      references: [users.id],
      relationName: "accounts",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  accounts: many(users_accounts, {
    relationName: "accounts",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: "testimonials",
    }),
    announcementsID: one(announcements, {
      fields: [payload_locked_documents_rels.announcementsID],
      references: [announcements.id],
      relationName: "announcements",
    }),
    faqCategoriesID: one(faq_categories, {
      fields: [payload_locked_documents_rels.faqCategoriesID],
      references: [faq_categories.id],
      relationName: "faqCategories",
    }),
    faqQuestionsID: one(faq_questions, {
      fields: [payload_locked_documents_rels.faqQuestionsID],
      references: [faq_questions.id],
      relationName: "faqQuestions",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_nav_blocks_link_item = relations(
  nav_blocks_link_item,
  ({ one }) => ({
    _parentID: one(nav, {
      fields: [nav_blocks_link_item._parentID],
      references: [nav.id],
      relationName: "_blocks_LinkItem",
    }),
  }),
);
export const relations_nav_blocks_nested_dropdown = relations(
  nav_blocks_nested_dropdown,
  ({ one }) => ({
    _parentID: one(nav, {
      fields: [nav_blocks_nested_dropdown._parentID],
      references: [nav.id],
      relationName: "_blocks_NestedDropdown",
    }),
  }),
);
export const relations_nav_blocks_visual_divider = relations(
  nav_blocks_visual_divider,
  ({ one }) => ({
    _parentID: one(nav, {
      fields: [nav_blocks_visual_divider._parentID],
      references: [nav.id],
      relationName: "_blocks_VisualDivider",
    }),
  }),
);
export const relations_nav_blocks_nav_dropdown = relations(
  nav_blocks_nav_dropdown,
  ({ one }) => ({
    _parentID: one(nav, {
      fields: [nav_blocks_nav_dropdown._parentID],
      references: [nav.id],
      relationName: "_blocks_NavDropdown",
    }),
  }),
);
export const relations_nav = relations(nav, ({ many }) => ({
  _blocks_LinkItem: many(nav_blocks_link_item, {
    relationName: "_blocks_LinkItem",
  }),
  _blocks_NestedDropdown: many(nav_blocks_nested_dropdown, {
    relationName: "_blocks_NestedDropdown",
  }),
  _blocks_VisualDivider: many(nav_blocks_visual_divider, {
    relationName: "_blocks_VisualDivider",
  }),
  _blocks_NavDropdown: many(nav_blocks_nav_dropdown, {
    relationName: "_blocks_NavDropdown",
  }),
}));
export const relations_home_blocks_text_card = relations(
  home_blocks_text_card,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_text_card._parentID],
      references: [home.id],
      relationName: "_blocks_TextCard",
    }),
    headerImage: one(media, {
      fields: [home_blocks_text_card.headerImage],
      references: [media.id],
      relationName: "headerImage",
    }),
  }),
);
export const relations_home_blocks_announcements_section = relations(
  home_blocks_announcements_section,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_announcements_section._parentID],
      references: [home.id],
      relationName: "_blocks_AnnouncementsSection",
    }),
    mainAnnouncement: one(announcements, {
      fields: [home_blocks_announcements_section.mainAnnouncement],
      references: [announcements.id],
      relationName: "mainAnnouncement",
    }),
  }),
);
export const relations_home_blocks_image_banner = relations(
  home_blocks_image_banner,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_image_banner._parentID],
      references: [home.id],
      relationName: "_blocks_ImageBanner",
    }),
    mainImage: one(media, {
      fields: [home_blocks_image_banner.mainImage],
      references: [media.id],
      relationName: "mainImage",
    }),
    bgImage: one(media, {
      fields: [home_blocks_image_banner.bgImage],
      references: [media.id],
      relationName: "bgImage",
    }),
  }),
);
export const relations_home_blocks_image_only_card = relations(
  home_blocks_image_only_card,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_image_only_card._parentID],
      references: [home.id],
      relationName: "_blocks_ImageOnlyCard",
    }),
    mainImage: one(media, {
      fields: [home_blocks_image_only_card.mainImage],
      references: [media.id],
      relationName: "mainImage",
    }),
  }),
);
export const relations_home_blocks_testimonial_slide = relations(
  home_blocks_testimonial_slide,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_testimonial_slide._parentID],
      references: [home.id],
      relationName: "_blocks_TestimonialSlide",
    }),
    testimonial: one(testimonials, {
      fields: [home_blocks_testimonial_slide.testimonial],
      references: [testimonials.id],
      relationName: "testimonial",
    }),
  }),
);
export const relations_home_blocks_testimonials_spinner = relations(
  home_blocks_testimonials_spinner,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_testimonials_spinner._parentID],
      references: [home.id],
      relationName: "_blocks_TestimonialsSpinner",
    }),
  }),
);
export const relations_home_blocks_featured_competitions = relations(
  home_blocks_featured_competitions,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_featured_competitions._parentID],
      references: [home.id],
      relationName: "_blocks_FeaturedCompetitions",
    }),
  }),
);
export const relations_home_blocks_two_blocks_leaf = relations(
  home_blocks_two_blocks_leaf,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_two_blocks_leaf._parentID],
      references: [home.id],
      relationName: "_blocks_twoBlocksLeaf",
    }),
  }),
);
export const relations_home_blocks_two_blocks_branch = relations(
  home_blocks_two_blocks_branch,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_two_blocks_branch._parentID],
      references: [home.id],
      relationName: "_blocks_twoBlocksBranch",
    }),
  }),
);
export const relations_home_blocks_two_blocks = relations(
  home_blocks_two_blocks,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_two_blocks._parentID],
      references: [home.id],
      relationName: "_blocks_twoBlocks",
    }),
  }),
);
export const relations_home_blocks_full_width = relations(
  home_blocks_full_width,
  ({ one }) => ({
    _parentID: one(home, {
      fields: [home_blocks_full_width._parentID],
      references: [home.id],
      relationName: "_blocks_fullWidth",
    }),
  }),
);
export const relations_home_rels = relations(home_rels, ({ one }) => ({
  parent: one(home, {
    fields: [home_rels.parent],
    references: [home.id],
    relationName: "_rels",
  }),
  announcementsID: one(announcements, {
    fields: [home_rels.announcementsID],
    references: [announcements.id],
    relationName: "announcements",
  }),
}));
export const relations_home = relations(home, ({ many }) => ({
  _blocks_TextCard: many(home_blocks_text_card, {
    relationName: "_blocks_TextCard",
  }),
  _blocks_AnnouncementsSection: many(home_blocks_announcements_section, {
    relationName: "_blocks_AnnouncementsSection",
  }),
  _blocks_ImageBanner: many(home_blocks_image_banner, {
    relationName: "_blocks_ImageBanner",
  }),
  _blocks_ImageOnlyCard: many(home_blocks_image_only_card, {
    relationName: "_blocks_ImageOnlyCard",
  }),
  _blocks_TestimonialSlide: many(home_blocks_testimonial_slide, {
    relationName: "_blocks_TestimonialSlide",
  }),
  _blocks_TestimonialsSpinner: many(home_blocks_testimonials_spinner, {
    relationName: "_blocks_TestimonialsSpinner",
  }),
  _blocks_FeaturedCompetitions: many(home_blocks_featured_competitions, {
    relationName: "_blocks_FeaturedCompetitions",
  }),
  _blocks_twoBlocksLeaf: many(home_blocks_two_blocks_leaf, {
    relationName: "_blocks_twoBlocksLeaf",
  }),
  _blocks_twoBlocksBranch: many(home_blocks_two_blocks_branch, {
    relationName: "_blocks_twoBlocksBranch",
  }),
  _blocks_twoBlocks: many(home_blocks_two_blocks, {
    relationName: "_blocks_twoBlocks",
  }),
  _blocks_fullWidth: many(home_blocks_full_width, {
    relationName: "_blocks_fullWidth",
  }),
  _rels: many(home_rels, {
    relationName: "_rels",
  }),
}));

type DatabaseSchema = {
  media: typeof media;
  testimonials: typeof testimonials;
  announcements: typeof announcements;
  faq_categories: typeof faq_categories;
  faq_questions: typeof faq_questions;
  users_accounts: typeof users_accounts;
  users: typeof users;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  nav_blocks_link_item: typeof nav_blocks_link_item;
  nav_blocks_nested_dropdown: typeof nav_blocks_nested_dropdown;
  nav_blocks_visual_divider: typeof nav_blocks_visual_divider;
  nav_blocks_nav_dropdown: typeof nav_blocks_nav_dropdown;
  nav: typeof nav;
  home_blocks_text_card: typeof home_blocks_text_card;
  home_blocks_announcements_section: typeof home_blocks_announcements_section;
  home_blocks_image_banner: typeof home_blocks_image_banner;
  home_blocks_image_only_card: typeof home_blocks_image_only_card;
  home_blocks_testimonial_slide: typeof home_blocks_testimonial_slide;
  home_blocks_testimonials_spinner: typeof home_blocks_testimonials_spinner;
  home_blocks_featured_competitions: typeof home_blocks_featured_competitions;
  home_blocks_two_blocks_leaf: typeof home_blocks_two_blocks_leaf;
  home_blocks_two_blocks_branch: typeof home_blocks_two_blocks_branch;
  home_blocks_two_blocks: typeof home_blocks_two_blocks;
  home_blocks_full_width: typeof home_blocks_full_width;
  home: typeof home;
  home_rels: typeof home_rels;
  relations_media: typeof relations_media;
  relations_testimonials: typeof relations_testimonials;
  relations_announcements: typeof relations_announcements;
  relations_faq_categories: typeof relations_faq_categories;
  relations_faq_questions: typeof relations_faq_questions;
  relations_users_accounts: typeof relations_users_accounts;
  relations_users: typeof relations_users;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_nav_blocks_link_item: typeof relations_nav_blocks_link_item;
  relations_nav_blocks_nested_dropdown: typeof relations_nav_blocks_nested_dropdown;
  relations_nav_blocks_visual_divider: typeof relations_nav_blocks_visual_divider;
  relations_nav_blocks_nav_dropdown: typeof relations_nav_blocks_nav_dropdown;
  relations_nav: typeof relations_nav;
  relations_home_blocks_text_card: typeof relations_home_blocks_text_card;
  relations_home_blocks_announcements_section: typeof relations_home_blocks_announcements_section;
  relations_home_blocks_image_banner: typeof relations_home_blocks_image_banner;
  relations_home_blocks_image_only_card: typeof relations_home_blocks_image_only_card;
  relations_home_blocks_testimonial_slide: typeof relations_home_blocks_testimonial_slide;
  relations_home_blocks_testimonials_spinner: typeof relations_home_blocks_testimonials_spinner;
  relations_home_blocks_featured_competitions: typeof relations_home_blocks_featured_competitions;
  relations_home_blocks_two_blocks_leaf: typeof relations_home_blocks_two_blocks_leaf;
  relations_home_blocks_two_blocks_branch: typeof relations_home_blocks_two_blocks_branch;
  relations_home_blocks_two_blocks: typeof relations_home_blocks_two_blocks;
  relations_home_blocks_full_width: typeof relations_home_blocks_full_width;
  relations_home_rels: typeof relations_home_rels;
  relations_home: typeof relations_home;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
