class RoundType < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[RoundType, ActiveRecord_Relation, String]

  module GeneratedAttributeMethods
    def id: () -> String

    def id=: (String) -> String

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ String?, String? ]

    def id_will_change!: () -> void

    def id_was: () -> String?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[String?]?

    def id_previously_was: () -> String?

    def id_before_last_save: () -> String?

    def id_change_to_be_saved: () -> Array[String?]?

    def id_in_database: () -> String?

    def saved_change_to_id: () -> Array[String?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def rank: () -> Integer

    def rank=: (Integer) -> Integer

    def rank?: () -> bool

    def rank_changed?: () -> bool

    def rank_change: () -> [ Integer?, Integer? ]

    def rank_will_change!: () -> void

    def rank_was: () -> Integer?

    def rank_previously_changed?: () -> bool

    def rank_previous_change: () -> Array[Integer?]?

    def rank_previously_was: () -> Integer?

    def rank_before_last_save: () -> Integer?

    def rank_change_to_be_saved: () -> Array[Integer?]?

    def rank_in_database: () -> Integer?

    def saved_change_to_rank: () -> Array[Integer?]?

    def saved_change_to_rank?: () -> bool

    def will_save_change_to_rank?: () -> bool

    def restore_rank!: () -> void

    def clear_rank_change: () -> void

    def name: () -> String

    def name=: (String) -> String

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def cellName: () -> String

    def cellName=: (String) -> String

    def cellName?: () -> bool

    def cellName_changed?: () -> bool

    def cellName_change: () -> [ String?, String? ]

    def cellName_will_change!: () -> void

    def cellName_was: () -> String?

    def cellName_previously_changed?: () -> bool

    def cellName_previous_change: () -> Array[String?]?

    def cellName_previously_was: () -> String?

    def cellName_before_last_save: () -> String?

    def cellName_change_to_be_saved: () -> Array[String?]?

    def cellName_in_database: () -> String?

    def saved_change_to_cellName: () -> Array[String?]?

    def saved_change_to_cellName?: () -> bool

    def will_save_change_to_cellName?: () -> bool

    def restore_cellName!: () -> void

    def clear_cellName_change: () -> void

    def final: () -> bool

    def final=: (bool) -> bool

    def final?: () -> bool

    def final_changed?: () -> bool

    def final_change: () -> [ bool?, bool? ]

    def final_will_change!: () -> void

    def final_was: () -> bool?

    def final_previously_changed?: () -> bool

    def final_previous_change: () -> Array[bool?]?

    def final_previously_was: () -> bool?

    def final_before_last_save: () -> bool?

    def final_change_to_be_saved: () -> Array[bool?]?

    def final_in_database: () -> bool?

    def saved_change_to_final: () -> Array[bool?]?

    def saved_change_to_final?: () -> bool

    def will_save_change_to_final?: () -> bool

    def restore_final!: () -> void

    def clear_final_change: () -> void
  end
  include GeneratedAttributeMethods
  def results: () -> Result::ActiveRecord_Associations_CollectionProxy
  def results=: (Result::ActiveRecord_Associations_CollectionProxy | Array[Result]) -> (Result::ActiveRecord_Associations_CollectionProxy | Array[Result])
  def result_ids: () -> Array[Integer]
  def result_ids=: (Array[Integer]) -> Array[Integer]
  def scrambles: () -> Scramble::ActiveRecord_Associations_CollectionProxy
  def scrambles=: (Scramble::ActiveRecord_Associations_CollectionProxy | Array[Scramble]) -> (Scramble::ActiveRecord_Associations_CollectionProxy | Array[Scramble])
  def scramble_ids: () -> Array[Integer]
  def scramble_ids=: (Array[Integer]) -> Array[Integer]

  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  def self.final_rounds: () -> ActiveRecord_Relation

  module GeneratedRelationMethods
    def final_rounds: () -> ActiveRecord_Relation
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[RoundType, String]
    include Enumerable[RoundType]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[RoundType, String]
  end
end
