class ScheduleActivity < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[ScheduleActivity, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def holder_type: () -> String

    def holder_type=: (String) -> String

    def holder_type?: () -> bool

    def holder_type_changed?: () -> bool

    def holder_type_change: () -> [ String?, String? ]

    def holder_type_will_change!: () -> void

    def holder_type_was: () -> String?

    def holder_type_previously_changed?: () -> bool

    def holder_type_previous_change: () -> Array[String?]?

    def holder_type_previously_was: () -> String?

    def holder_type_before_last_save: () -> String?

    def holder_type_change_to_be_saved: () -> Array[String?]?

    def holder_type_in_database: () -> String?

    def saved_change_to_holder_type: () -> Array[String?]?

    def saved_change_to_holder_type?: () -> bool

    def will_save_change_to_holder_type?: () -> bool

    def restore_holder_type!: () -> void

    def clear_holder_type_change: () -> void

    def holder_id: () -> Integer

    def holder_id=: (Integer) -> Integer

    def holder_id?: () -> bool

    def holder_id_changed?: () -> bool

    def holder_id_change: () -> [ Integer?, Integer? ]

    def holder_id_will_change!: () -> void

    def holder_id_was: () -> Integer?

    def holder_id_previously_changed?: () -> bool

    def holder_id_previous_change: () -> Array[Integer?]?

    def holder_id_previously_was: () -> Integer?

    def holder_id_before_last_save: () -> Integer?

    def holder_id_change_to_be_saved: () -> Array[Integer?]?

    def holder_id_in_database: () -> Integer?

    def saved_change_to_holder_id: () -> Array[Integer?]?

    def saved_change_to_holder_id?: () -> bool

    def will_save_change_to_holder_id?: () -> bool

    def restore_holder_id!: () -> void

    def clear_holder_id_change: () -> void

    def wcif_id: () -> Integer

    def wcif_id=: (Integer) -> Integer

    def wcif_id?: () -> bool

    def wcif_id_changed?: () -> bool

    def wcif_id_change: () -> [ Integer?, Integer? ]

    def wcif_id_will_change!: () -> void

    def wcif_id_was: () -> Integer?

    def wcif_id_previously_changed?: () -> bool

    def wcif_id_previous_change: () -> Array[Integer?]?

    def wcif_id_previously_was: () -> Integer?

    def wcif_id_before_last_save: () -> Integer?

    def wcif_id_change_to_be_saved: () -> Array[Integer?]?

    def wcif_id_in_database: () -> Integer?

    def saved_change_to_wcif_id: () -> Array[Integer?]?

    def saved_change_to_wcif_id?: () -> bool

    def will_save_change_to_wcif_id?: () -> bool

    def restore_wcif_id!: () -> void

    def clear_wcif_id_change: () -> void

    def name: () -> String

    def name=: (String) -> String

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def activity_code: () -> String

    def activity_code=: (String) -> String

    def activity_code?: () -> bool

    def activity_code_changed?: () -> bool

    def activity_code_change: () -> [ String?, String? ]

    def activity_code_will_change!: () -> void

    def activity_code_was: () -> String?

    def activity_code_previously_changed?: () -> bool

    def activity_code_previous_change: () -> Array[String?]?

    def activity_code_previously_was: () -> String?

    def activity_code_before_last_save: () -> String?

    def activity_code_change_to_be_saved: () -> Array[String?]?

    def activity_code_in_database: () -> String?

    def saved_change_to_activity_code: () -> Array[String?]?

    def saved_change_to_activity_code?: () -> bool

    def will_save_change_to_activity_code?: () -> bool

    def restore_activity_code!: () -> void

    def clear_activity_code_change: () -> void

    def start_time: () -> ActiveSupport::TimeWithZone

    def start_time=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def start_time?: () -> bool

    def start_time_changed?: () -> bool

    def start_time_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def start_time_will_change!: () -> void

    def start_time_was: () -> ActiveSupport::TimeWithZone?

    def start_time_previously_changed?: () -> bool

    def start_time_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def start_time_previously_was: () -> ActiveSupport::TimeWithZone?

    def start_time_before_last_save: () -> ActiveSupport::TimeWithZone?

    def start_time_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def start_time_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_start_time: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_start_time?: () -> bool

    def will_save_change_to_start_time?: () -> bool

    def restore_start_time!: () -> void

    def clear_start_time_change: () -> void

    def end_time: () -> ActiveSupport::TimeWithZone

    def end_time=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def end_time?: () -> bool

    def end_time_changed?: () -> bool

    def end_time_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def end_time_will_change!: () -> void

    def end_time_was: () -> ActiveSupport::TimeWithZone?

    def end_time_previously_changed?: () -> bool

    def end_time_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def end_time_previously_was: () -> ActiveSupport::TimeWithZone?

    def end_time_before_last_save: () -> ActiveSupport::TimeWithZone?

    def end_time_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def end_time_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_end_time: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_end_time?: () -> bool

    def will_save_change_to_end_time?: () -> bool

    def restore_end_time!: () -> void

    def clear_end_time_change: () -> void

    def scramble_set_id: () -> Integer?

    def scramble_set_id=: (Integer?) -> Integer?

    def scramble_set_id?: () -> bool

    def scramble_set_id_changed?: () -> bool

    def scramble_set_id_change: () -> [ Integer?, Integer? ]

    def scramble_set_id_will_change!: () -> void

    def scramble_set_id_was: () -> Integer?

    def scramble_set_id_previously_changed?: () -> bool

    def scramble_set_id_previous_change: () -> Array[Integer?]?

    def scramble_set_id_previously_was: () -> Integer?

    def scramble_set_id_before_last_save: () -> Integer?

    def scramble_set_id_change_to_be_saved: () -> Array[Integer?]?

    def scramble_set_id_in_database: () -> Integer?

    def saved_change_to_scramble_set_id: () -> Array[Integer?]?

    def saved_change_to_scramble_set_id?: () -> bool

    def will_save_change_to_scramble_set_id?: () -> bool

    def restore_scramble_set_id!: () -> void

    def clear_scramble_set_id_change: () -> void

    def created_at: () -> ActiveSupport::TimeWithZone

    def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ActiveSupport::TimeWithZone

    def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void
  end
  include GeneratedAttributeMethods
  def child_activities: () -> ScheduleActivity::ActiveRecord_Associations_CollectionProxy
  def child_activities=: (ScheduleActivity::ActiveRecord_Associations_CollectionProxy | Array[ScheduleActivity]) -> (ScheduleActivity::ActiveRecord_Associations_CollectionProxy | Array[ScheduleActivity])
  def child_activity_ids: () -> Array[Integer]
  def child_activity_ids=: (Array[Integer]) -> Array[Integer]
  def wcif_extensions: () -> WcifExtension::ActiveRecord_Associations_CollectionProxy
  def wcif_extensions=: (WcifExtension::ActiveRecord_Associations_CollectionProxy | Array[WcifExtension]) -> (WcifExtension::ActiveRecord_Associations_CollectionProxy | Array[WcifExtension])
  def wcif_extension_ids: () -> Array[Integer]
  def wcif_extension_ids=: (Array[Integer]) -> Array[Integer]
  def assignments: () -> Assignment::ActiveRecord_Associations_CollectionProxy
  def assignments=: (Assignment::ActiveRecord_Associations_CollectionProxy | Array[Assignment]) -> (Assignment::ActiveRecord_Associations_CollectionProxy | Array[Assignment])
  def assignment_ids: () -> Array[Integer]
  def assignment_ids=: (Array[Integer]) -> Array[Integer]

  def holder: () -> untyped
  def holder=: (untyped?) -> untyped?
  def reload_holder: () -> untyped?
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[ScheduleActivity, Integer]
    include Enumerable[ScheduleActivity]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[ScheduleActivity, Integer]
  end
end
