class Team < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[Team, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def friendly_id: () -> String?

    def friendly_id=: (String?) -> String?

    def friendly_id?: () -> bool

    def friendly_id_changed?: () -> bool

    def friendly_id_change: () -> [ String?, String? ]

    def friendly_id_will_change!: () -> void

    def friendly_id_was: () -> String?

    def friendly_id_previously_changed?: () -> bool

    def friendly_id_previous_change: () -> Array[String?]?

    def friendly_id_previously_was: () -> String?

    def friendly_id_before_last_save: () -> String?

    def friendly_id_change_to_be_saved: () -> Array[String?]?

    def friendly_id_in_database: () -> String?

    def saved_change_to_friendly_id: () -> Array[String?]?

    def saved_change_to_friendly_id?: () -> bool

    def will_save_change_to_friendly_id?: () -> bool

    def restore_friendly_id!: () -> void

    def clear_friendly_id_change: () -> void

    def created_at: () -> ActiveSupport::TimeWithZone

    def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ActiveSupport::TimeWithZone

    def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def email: () -> String?

    def email=: (String?) -> String?

    def email?: () -> bool

    def email_changed?: () -> bool

    def email_change: () -> [ String?, String? ]

    def email_will_change!: () -> void

    def email_was: () -> String?

    def email_previously_changed?: () -> bool

    def email_previous_change: () -> Array[String?]?

    def email_previously_was: () -> String?

    def email_before_last_save: () -> String?

    def email_change_to_be_saved: () -> Array[String?]?

    def email_in_database: () -> String?

    def saved_change_to_email: () -> Array[String?]?

    def saved_change_to_email?: () -> bool

    def will_save_change_to_email?: () -> bool

    def restore_email!: () -> void

    def clear_email_change: () -> void

    def hidden: () -> bool

    def hidden=: (bool) -> bool

    def hidden?: () -> bool

    def hidden_changed?: () -> bool

    def hidden_change: () -> [ bool?, bool? ]

    def hidden_will_change!: () -> void

    def hidden_was: () -> bool?

    def hidden_previously_changed?: () -> bool

    def hidden_previous_change: () -> Array[bool?]?

    def hidden_previously_was: () -> bool?

    def hidden_before_last_save: () -> bool?

    def hidden_change_to_be_saved: () -> Array[bool?]?

    def hidden_in_database: () -> bool?

    def saved_change_to_hidden: () -> Array[bool?]?

    def saved_change_to_hidden?: () -> bool

    def will_save_change_to_hidden?: () -> bool

    def restore_hidden!: () -> void

    def clear_hidden_change: () -> void
  end
  include GeneratedAttributeMethods
  def team_members: () -> TeamMember::ActiveRecord_Associations_CollectionProxy
  def team_members=: (TeamMember::ActiveRecord_Associations_CollectionProxy | Array[TeamMember]) -> (TeamMember::ActiveRecord_Associations_CollectionProxy | Array[TeamMember])
  def team_member_ids: () -> Array[Integer]
  def team_member_ids=: (Array[Integer]) -> Array[Integer]
  def current_members: () -> TeamMember::ActiveRecord_Associations_CollectionProxy
  def current_members=: (TeamMember::ActiveRecord_Associations_CollectionProxy | Array[TeamMember]) -> (TeamMember::ActiveRecord_Associations_CollectionProxy | Array[TeamMember])
  def current_member_ids: () -> Array[Integer]
  def current_member_ids=: (Array[Integer]) -> Array[Integer]
  def leader: () -> TeamMember?
  def leader=: (TeamMember?) -> TeamMember?
  def build_leader: (untyped) -> TeamMember
  def create_leader: (untyped) -> TeamMember
  def create_leader!: (untyped) -> TeamMember
  def reload_leader: () -> TeamMember?

  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  def self.with_hidden: () -> ActiveRecord_Relation
  def self.official: () -> ActiveRecord_Relation

  module GeneratedRelationMethods
    def with_hidden: () -> ActiveRecord_Relation

    def official: () -> ActiveRecord_Relation
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Team, Integer]
    include Enumerable[Team]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Team, Integer]
  end
end
