interface _RbsRailsPathHelpers
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def rails_mailers_path: (*untyped) -> String
  def native_oauth_authorization_path: (*untyped) -> String
  def oauth_authorization_path: (*untyped) -> String
  def oauth_token_path: (*untyped) -> String
  def oauth_revoke_path: (*untyped) -> String
  def oauth_introspect_path: (*untyped) -> String
  def oauth_applications_path: (*untyped) -> String
  def new_oauth_application_path: (*untyped) -> String
  def edit_oauth_application_path: (*untyped) -> String
  def oauth_application_path: (*untyped) -> String
  def oauth_authorized_applications_path: (*untyped) -> String
  def oauth_authorized_application_path: (*untyped) -> String
  def oauth_token_info_path: (*untyped) -> String
  def starburst_path: (*untyped) -> String
  def new_user_password_path: (*untyped) -> String
  def edit_user_password_path: (*untyped) -> String
  def user_password_path: (*untyped) -> String
  def new_user_confirmation_path: (*untyped) -> String
  def user_confirmation_path: (*untyped) -> String
  def new_user_session_path: (*untyped) -> String
  def user_session_path: (*untyped) -> String
  def destroy_user_session_path: (*untyped) -> String
  def cancel_user_registration_path: (*untyped) -> String
  def new_user_registration_path: (*untyped) -> String
  def user_registration_path: (*untyped) -> String
  def users_generate_email_otp_path: (*untyped) -> String
  def users_authenticate_sensitive_path: (*untyped) -> String
  def destroy_other_user_sessions_path: (*untyped) -> String
  def registration_payment_refund_path: (*untyped) -> String
  def registration_payment_intent_path: (*untyped) -> String
  def users_path: (*untyped) -> String
  def edit_user_path: (*untyped) -> String
  def user_path: (*untyped) -> String
  def profile_edit_path: (*untyped) -> String
  def profile_enable_2fa_path: (*untyped) -> String
  def profile_disable_2fa_path: (*untyped) -> String
  def profile_generate_2fa_backup_path: (*untyped) -> String
  def profile_acknowledge_cookies_path: (*untyped) -> String
  def profile_claim_wca_id_path: (*untyped) -> String
  def profile_claim_wca_id_select_nearby_delegate_path: (*untyped) -> String
  def users_avatar_thumbnail_edit_path: (*untyped) -> String
  def users_pending_avatar_thumbnail_edit_path: (*untyped) -> String
  def admin_avatars_path: (*untyped) -> String
  def map_path: (*untyped) -> String
  def my_comps_path: (*untyped) -> String
  def competitions_for_senior_path: (*untyped) -> String
  def bookmark_path: (*untyped) -> String
  def unbookmark_path: (*untyped) -> String
  def competition_results_podiums_path: (*untyped) -> String
  def competition_results_all_path: (*untyped) -> String
  def competition_results_by_person_path: (*untyped) -> String
  def competition_scrambles_path: (*untyped) -> String
  def competition_registrations_do_actions_for_selected_path: (*untyped) -> String
  def competition_registrations_export_path: (*untyped) -> String
  def competition_registrations_import_path: (*untyped) -> String
  def competition_registrations_do_import_path: (*untyped) -> String
  def competition_registrations_add_path: (*untyped) -> String
  def competition_registrations_do_add_path: (*untyped) -> String
  def competition_psych_sheet_path: (*untyped) -> String
  def competition_psych_sheet_event_path: (*untyped) -> String
  def competition_registrations_path: (*untyped) -> String
  def edit_registration_path: (*untyped) -> String
  def registration_path: (*untyped) -> String
  def competition_edit_registrations_path: (*untyped) -> String
  def competition_register_path: (*untyped) -> String
  def competition_payment_success_path: (*untyped) -> String
  def competition_register_require_sign_in_path: (*untyped) -> String
  def competition_tabs_path: (*untyped) -> String
  def new_competition_tab_path: (*untyped) -> String
  def edit_competition_tab_path: (*untyped) -> String
  def competition_tab_path: (*untyped) -> String
  def competition_tab_reorder_path: (*untyped) -> String
  def competition_submit_results_edit_path: (*untyped) -> String
  def competition_submit_results_path: (*untyped) -> String
  def competition_upload_results_json_path: (*untyped) -> String
  def competition_admin_upload_results_edit_path: (*untyped) -> String
  def competition_admin_check_existing_results_path: (*untyped) -> String
  def competition_admin_upload_results_path: (*untyped) -> String
  def competition_clear_results_submission_path: (*untyped) -> String
  def competitions_path: (*untyped) -> String
  def new_competition_path: (*untyped) -> String
  def edit_competition_path: (*untyped) -> String
  def competition_path: (*untyped) -> String
  def admin_run_validators_path: (*untyped) -> String
  def delegate_report_edit_path: (*untyped) -> String
  def delegate_report_path: (*untyped) -> String
  def admin_edit_competition_path: (*untyped) -> String
  def competitions_payment_setup_path: (*untyped) -> String
  def competitions_stripe_connect_path: (*untyped) -> String
  def edit_events_path: (*untyped) -> String
  def edit_schedule_path: (*untyped) -> String
  def nearby_competitions_path: (*untyped) -> String
  def time_until_competition_path: (*untyped) -> String
  def clone_competition_path: (*untyped) -> String
  def currency_convert_path: (*untyped) -> String
  def results_rankings_path: (*untyped) -> String
  def results_rankings_333mbf_average_path: (*untyped) -> String
  def rankings_path: (*untyped) -> String
  def records_path: (*untyped) -> String
  def validate_media_path: (*untyped) -> String
  def media_path: (*untyped) -> String
  def new_medium_path: (*untyped) -> String
  def edit_medium_path: (*untyped) -> String
  def medium_path: (*untyped) -> String
  def persons_path: (*untyped) -> String
  def person_path: (*untyped) -> String
  def polls_path: (*untyped) -> String
  def new_poll_path: (*untyped) -> String
  def edit_poll_path: (*untyped) -> String
  def poll_path: (*untyped) -> String
  def polls_vote_path: (*untyped) -> String
  def polls_results_path: (*untyped) -> String
  def teams_path: (*untyped) -> String
  def edit_team_path: (*untyped) -> String
  def team_path: (*untyped) -> String
  def votes_path: (*untyped) -> String
  def vote_path: (*untyped) -> String
  def competition_post_announcement_path: (*untyped) -> String
  def competition_cancel_path: (*untyped) -> String
  def competition_post_results_path: (*untyped) -> String
  def panel_path: (*untyped) -> String
  def panel_delegate_crash_course_path: (*untyped) -> String
  def pending_claims_path: (*untyped) -> String
  def panel_seniors_path: (*untyped) -> String
  def notifications_path: (*untyped) -> String
  def root_path: (*untyped) -> String
  def posts_path: (*untyped) -> String
  def new_post_path: (*untyped) -> String
  def edit_post_path: (*untyped) -> String
  def post_path: (*untyped) -> String
  def rss_path: (*untyped) -> String
  def upload_image_path: (*untyped) -> String
  def delegates_stats_path: (*untyped) -> String
  def robots_path: (*untyped) -> String
  def server_status_path: (*untyped) -> String
  def translations_path: (*untyped) -> String
  def translations_status_path: (*untyped) -> String
  def translations_edit_path: (*untyped) -> String
  def translations_update_path: (*untyped) -> String
  def about_path: (*untyped) -> String
  def teams_committees_path: (*untyped) -> String
  def documents_path: (*untyped) -> String
  def education_path: (*untyped) -> String
  def delegates_path: (*untyped) -> String
  def disclaimer_path: (*untyped) -> String
  def contact_path: (*untyped) -> String
  def speedcubing_history_path: (*untyped) -> String
  def privacy_path: (*untyped) -> String
  def faq_path: (*untyped) -> String
  def score_tools_path: (*untyped) -> String
  def logo_path: (*untyped) -> String
  def media_instagram_path: (*untyped) -> String
  def wca_workbook_assistant_path: (*untyped) -> String
  def wca_workbook_assistant_versions_path: (*untyped) -> String
  def organizer_guidelines_path: (*untyped) -> String
  def tutorial_path: (*untyped) -> String
  def new_regional_organization_path: (*untyped) -> String
  def edit_regional_organization_path: (*untyped) -> String
  def regional_organization_path: (*untyped) -> String
  def organizations_path: (*untyped) -> String
  def admin_regional_organizations_path: (*untyped) -> String
  def regional_organizations_new_path: (*untyped) -> String
  def disciplinary_path: (*untyped) -> String
  def contact_website_path: (*untyped) -> String
  def contact_dob_path: (*untyped) -> String
  def regulations_path: (*untyped) -> String
  def admin_path: (*untyped) -> String
  def eligible_voters_path: (*untyped) -> String
  def leader_senior_voters_path: (*untyped) -> String
  def admin_merge_people_path: (*untyped) -> String
  def admin_edit_person_path: (*untyped) -> String
  def admin_update_person_path: (*untyped) -> String
  def admin_person_data_path: (*untyped) -> String
  def admin_compute_auxiliary_data_path: (*untyped) -> String
  def admin_do_compute_auxiliary_data_path: (*untyped) -> String
  def admin_update_statistics_path: (*untyped) -> String
  def admin_anonymize_person_path: (*untyped) -> String
  def admin_reassign_wca_id_path: (*untyped) -> String
  def admin_validate_reassign_wca_id_path: (*untyped) -> String
  def search_path: (*untyped) -> String
  def render_markdown_path: (*untyped) -> String
  def update_locale_path: (*untyped) -> String
  def relations_path: (*untyped) -> String
  def relation_path: (*untyped) -> String
  def wfc_path: (*untyped) -> String
  def wfc_competitions_export_path: (*untyped) -> String
  def country_bands_path: (*untyped) -> String
  def edit_country_band_path: (*untyped) -> String
  def country_band_path: (*untyped) -> String
  def forums_path: (*untyped) -> String
  def forum_path: (*untyped) -> String
  def forum_topic_path: (*untyped) -> String
  def incident_mark_as_path: (*untyped) -> String
  def incidents_path: (*untyped) -> String
  def new_incident_path: (*untyped) -> String
  def edit_incident_path: (*untyped) -> String
  def incident_path: (*untyped) -> String
  def sso_discourse_path: (*untyped) -> String
  def api_path: (*untyped) -> String
  def api_v0_path: (*untyped) -> String
  def api_v0_me_path: (*untyped) -> String
  def api_v0_auth_results_path: (*untyped) -> String
  def api_v0_export_public_path: (*untyped) -> String
  def api_v0_scramble_program_path: (*untyped) -> String
  def api_v0_search_path: (*untyped) -> String
  def api_v0_search_posts_path: (*untyped) -> String
  def api_v0_search_competitions_path: (*untyped) -> String
  def api_v0_search_users_path: (*untyped) -> String
  def api_v0_search_regulations_path: (*untyped) -> String
  def api_v0_delegates_path: (*untyped) -> String
  def api_v0_persons_path: (*untyped) -> String
  def api_v0_person_path: (*untyped) -> String
  def api_v0_person_results_path: (*untyped) -> String
  def api_v0_geocoding_search_path: (*untyped) -> String
  def api_v0_competition_wcif_path: (*untyped) -> String
  def api_v0_competition_wcif_public_path: (*untyped) -> String
  def api_v0_competition_results_path: (*untyped) -> String
  def api_v0_competition_event_results_path: (*untyped) -> String
  def api_v0_competition_competitors_path: (*untyped) -> String
  def api_v0_competition_registrations_path: (*untyped) -> String
  def api_v0_competition_schedule_path: (*untyped) -> String
  def api_v0_competition_scrambles_path: (*untyped) -> String
  def api_v0_competition_event_scrambles_path: (*untyped) -> String
  def api_v0_competition_update_wcif_path: (*untyped) -> String
  def api_v0_competitions_path: (*untyped) -> String
  def api_v0_competition_path: (*untyped) -> String
  def api_v0_records_path: (*untyped) -> String
  def rails_postmark_inbound_emails_path: (*untyped) -> String
  def rails_relay_inbound_emails_path: (*untyped) -> String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> String
  def rails_mandrill_inbound_emails_path: (*untyped) -> String
  def rails_mailgun_inbound_emails_path: (*untyped) -> String
  def rails_conductor_inbound_emails_path: (*untyped) -> String
  def new_rails_conductor_inbound_email_path: (*untyped) -> String
  def edit_rails_conductor_inbound_email_path: (*untyped) -> String
  def rails_conductor_inbound_email_path: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> String
  def rails_service_blob_path: (*untyped) -> String
  def rails_service_blob_proxy_path: (*untyped) -> String
  def rails_blob_representation_path: (*untyped) -> String
  def rails_blob_representation_proxy_path: (*untyped) -> String
  def rails_disk_service_path: (*untyped) -> String
  def update_rails_disk_service_path: (*untyped) -> String
  def rails_direct_uploads_path: (*untyped) -> String
  def rails_representation_path: (*untyped) -> String
  def rails_blob_path: (*untyped) -> String
  def rails_storage_proxy_path: (*untyped) -> String
  def rails_storage_redirect_path: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def native_oauth_authorization_url: (*untyped) -> String
  def oauth_authorization_url: (*untyped) -> String
  def oauth_token_url: (*untyped) -> String
  def oauth_revoke_url: (*untyped) -> String
  def oauth_introspect_url: (*untyped) -> String
  def oauth_applications_url: (*untyped) -> String
  def new_oauth_application_url: (*untyped) -> String
  def edit_oauth_application_url: (*untyped) -> String
  def oauth_application_url: (*untyped) -> String
  def oauth_authorized_applications_url: (*untyped) -> String
  def oauth_authorized_application_url: (*untyped) -> String
  def oauth_token_info_url: (*untyped) -> String
  def starburst_url: (*untyped) -> String
  def new_user_password_url: (*untyped) -> String
  def edit_user_password_url: (*untyped) -> String
  def user_password_url: (*untyped) -> String
  def new_user_confirmation_url: (*untyped) -> String
  def user_confirmation_url: (*untyped) -> String
  def new_user_session_url: (*untyped) -> String
  def user_session_url: (*untyped) -> String
  def destroy_user_session_url: (*untyped) -> String
  def cancel_user_registration_url: (*untyped) -> String
  def new_user_registration_url: (*untyped) -> String
  def user_registration_url: (*untyped) -> String
  def users_generate_email_otp_url: (*untyped) -> String
  def users_authenticate_sensitive_url: (*untyped) -> String
  def destroy_other_user_sessions_url: (*untyped) -> String
  def registration_payment_refund_url: (*untyped) -> String
  def registration_payment_intent_url: (*untyped) -> String
  def users_url: (*untyped) -> String
  def edit_user_url: (*untyped) -> String
  def user_url: (*untyped) -> String
  def profile_edit_url: (*untyped) -> String
  def profile_enable_2fa_url: (*untyped) -> String
  def profile_disable_2fa_url: (*untyped) -> String
  def profile_generate_2fa_backup_url: (*untyped) -> String
  def profile_acknowledge_cookies_url: (*untyped) -> String
  def profile_claim_wca_id_url: (*untyped) -> String
  def profile_claim_wca_id_select_nearby_delegate_url: (*untyped) -> String
  def users_avatar_thumbnail_edit_url: (*untyped) -> String
  def users_pending_avatar_thumbnail_edit_url: (*untyped) -> String
  def admin_avatars_url: (*untyped) -> String
  def map_url: (*untyped) -> String
  def my_comps_url: (*untyped) -> String
  def competitions_for_senior_url: (*untyped) -> String
  def bookmark_url: (*untyped) -> String
  def unbookmark_url: (*untyped) -> String
  def competition_results_podiums_url: (*untyped) -> String
  def competition_results_all_url: (*untyped) -> String
  def competition_results_by_person_url: (*untyped) -> String
  def competition_scrambles_url: (*untyped) -> String
  def competition_registrations_do_actions_for_selected_url: (*untyped) -> String
  def competition_registrations_export_url: (*untyped) -> String
  def competition_registrations_import_url: (*untyped) -> String
  def competition_registrations_do_import_url: (*untyped) -> String
  def competition_registrations_add_url: (*untyped) -> String
  def competition_registrations_do_add_url: (*untyped) -> String
  def competition_psych_sheet_url: (*untyped) -> String
  def competition_psych_sheet_event_url: (*untyped) -> String
  def competition_registrations_url: (*untyped) -> String
  def edit_registration_url: (*untyped) -> String
  def registration_url: (*untyped) -> String
  def competition_edit_registrations_url: (*untyped) -> String
  def competition_register_url: (*untyped) -> String
  def competition_payment_success_url: (*untyped) -> String
  def competition_register_require_sign_in_url: (*untyped) -> String
  def competition_tabs_url: (*untyped) -> String
  def new_competition_tab_url: (*untyped) -> String
  def edit_competition_tab_url: (*untyped) -> String
  def competition_tab_url: (*untyped) -> String
  def competition_tab_reorder_url: (*untyped) -> String
  def competition_submit_results_edit_url: (*untyped) -> String
  def competition_submit_results_url: (*untyped) -> String
  def competition_upload_results_json_url: (*untyped) -> String
  def competition_admin_upload_results_edit_url: (*untyped) -> String
  def competition_admin_check_existing_results_url: (*untyped) -> String
  def competition_admin_upload_results_url: (*untyped) -> String
  def competition_clear_results_submission_url: (*untyped) -> String
  def competitions_url: (*untyped) -> String
  def new_competition_url: (*untyped) -> String
  def edit_competition_url: (*untyped) -> String
  def competition_url: (*untyped) -> String
  def admin_run_validators_url: (*untyped) -> String
  def delegate_report_edit_url: (*untyped) -> String
  def delegate_report_url: (*untyped) -> String
  def admin_edit_competition_url: (*untyped) -> String
  def competitions_payment_setup_url: (*untyped) -> String
  def competitions_stripe_connect_url: (*untyped) -> String
  def edit_events_url: (*untyped) -> String
  def edit_schedule_url: (*untyped) -> String
  def nearby_competitions_url: (*untyped) -> String
  def time_until_competition_url: (*untyped) -> String
  def clone_competition_url: (*untyped) -> String
  def currency_convert_url: (*untyped) -> String
  def results_rankings_url: (*untyped) -> String
  def results_rankings_333mbf_average_url: (*untyped) -> String
  def rankings_url: (*untyped) -> String
  def records_url: (*untyped) -> String
  def validate_media_url: (*untyped) -> String
  def media_url: (*untyped) -> String
  def new_medium_url: (*untyped) -> String
  def edit_medium_url: (*untyped) -> String
  def medium_url: (*untyped) -> String
  def persons_url: (*untyped) -> String
  def person_url: (*untyped) -> String
  def polls_url: (*untyped) -> String
  def new_poll_url: (*untyped) -> String
  def edit_poll_url: (*untyped) -> String
  def poll_url: (*untyped) -> String
  def polls_vote_url: (*untyped) -> String
  def polls_results_url: (*untyped) -> String
  def teams_url: (*untyped) -> String
  def edit_team_url: (*untyped) -> String
  def team_url: (*untyped) -> String
  def votes_url: (*untyped) -> String
  def vote_url: (*untyped) -> String
  def competition_post_announcement_url: (*untyped) -> String
  def competition_cancel_url: (*untyped) -> String
  def competition_post_results_url: (*untyped) -> String
  def panel_url: (*untyped) -> String
  def panel_delegate_crash_course_url: (*untyped) -> String
  def pending_claims_url: (*untyped) -> String
  def panel_seniors_url: (*untyped) -> String
  def notifications_url: (*untyped) -> String
  def root_url: (*untyped) -> String
  def posts_url: (*untyped) -> String
  def new_post_url: (*untyped) -> String
  def edit_post_url: (*untyped) -> String
  def post_url: (*untyped) -> String
  def rss_url: (*untyped) -> String
  def upload_image_url: (*untyped) -> String
  def delegates_stats_url: (*untyped) -> String
  def robots_url: (*untyped) -> String
  def server_status_url: (*untyped) -> String
  def translations_url: (*untyped) -> String
  def translations_status_url: (*untyped) -> String
  def translations_edit_url: (*untyped) -> String
  def translations_update_url: (*untyped) -> String
  def about_url: (*untyped) -> String
  def teams_committees_url: (*untyped) -> String
  def documents_url: (*untyped) -> String
  def education_url: (*untyped) -> String
  def delegates_url: (*untyped) -> String
  def disclaimer_url: (*untyped) -> String
  def contact_url: (*untyped) -> String
  def speedcubing_history_url: (*untyped) -> String
  def privacy_url: (*untyped) -> String
  def faq_url: (*untyped) -> String
  def score_tools_url: (*untyped) -> String
  def logo_url: (*untyped) -> String
  def media_instagram_url: (*untyped) -> String
  def wca_workbook_assistant_url: (*untyped) -> String
  def wca_workbook_assistant_versions_url: (*untyped) -> String
  def organizer_guidelines_url: (*untyped) -> String
  def tutorial_url: (*untyped) -> String
  def new_regional_organization_url: (*untyped) -> String
  def edit_regional_organization_url: (*untyped) -> String
  def regional_organization_url: (*untyped) -> String
  def organizations_url: (*untyped) -> String
  def admin_regional_organizations_url: (*untyped) -> String
  def regional_organizations_new_url: (*untyped) -> String
  def disciplinary_url: (*untyped) -> String
  def contact_website_url: (*untyped) -> String
  def contact_dob_url: (*untyped) -> String
  def regulations_url: (*untyped) -> String
  def admin_url: (*untyped) -> String
  def eligible_voters_url: (*untyped) -> String
  def leader_senior_voters_url: (*untyped) -> String
  def admin_merge_people_url: (*untyped) -> String
  def admin_edit_person_url: (*untyped) -> String
  def admin_update_person_url: (*untyped) -> String
  def admin_person_data_url: (*untyped) -> String
  def admin_compute_auxiliary_data_url: (*untyped) -> String
  def admin_do_compute_auxiliary_data_url: (*untyped) -> String
  def admin_update_statistics_url: (*untyped) -> String
  def admin_anonymize_person_url: (*untyped) -> String
  def admin_reassign_wca_id_url: (*untyped) -> String
  def admin_validate_reassign_wca_id_url: (*untyped) -> String
  def search_url: (*untyped) -> String
  def render_markdown_url: (*untyped) -> String
  def update_locale_url: (*untyped) -> String
  def relations_url: (*untyped) -> String
  def relation_url: (*untyped) -> String
  def wfc_url: (*untyped) -> String
  def wfc_competitions_export_url: (*untyped) -> String
  def country_bands_url: (*untyped) -> String
  def edit_country_band_url: (*untyped) -> String
  def country_band_url: (*untyped) -> String
  def forums_url: (*untyped) -> String
  def forum_url: (*untyped) -> String
  def forum_topic_url: (*untyped) -> String
  def incident_mark_as_url: (*untyped) -> String
  def incidents_url: (*untyped) -> String
  def new_incident_url: (*untyped) -> String
  def edit_incident_url: (*untyped) -> String
  def incident_url: (*untyped) -> String
  def sso_discourse_url: (*untyped) -> String
  def api_url: (*untyped) -> String
  def api_v0_url: (*untyped) -> String
  def api_v0_me_url: (*untyped) -> String
  def api_v0_auth_results_url: (*untyped) -> String
  def api_v0_export_public_url: (*untyped) -> String
  def api_v0_scramble_program_url: (*untyped) -> String
  def api_v0_search_url: (*untyped) -> String
  def api_v0_search_posts_url: (*untyped) -> String
  def api_v0_search_competitions_url: (*untyped) -> String
  def api_v0_search_users_url: (*untyped) -> String
  def api_v0_search_regulations_url: (*untyped) -> String
  def api_v0_delegates_url: (*untyped) -> String
  def api_v0_persons_url: (*untyped) -> String
  def api_v0_person_url: (*untyped) -> String
  def api_v0_person_results_url: (*untyped) -> String
  def api_v0_geocoding_search_url: (*untyped) -> String
  def api_v0_competition_wcif_url: (*untyped) -> String
  def api_v0_competition_wcif_public_url: (*untyped) -> String
  def api_v0_competition_results_url: (*untyped) -> String
  def api_v0_competition_event_results_url: (*untyped) -> String
  def api_v0_competition_competitors_url: (*untyped) -> String
  def api_v0_competition_registrations_url: (*untyped) -> String
  def api_v0_competition_schedule_url: (*untyped) -> String
  def api_v0_competition_scrambles_url: (*untyped) -> String
  def api_v0_competition_event_scrambles_url: (*untyped) -> String
  def api_v0_competition_update_wcif_url: (*untyped) -> String
  def api_v0_competitions_url: (*untyped) -> String
  def api_v0_competition_url: (*untyped) -> String
  def api_v0_records_url: (*untyped) -> String
  def rails_postmark_inbound_emails_url: (*untyped) -> String
  def rails_relay_inbound_emails_url: (*untyped) -> String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> String
  def rails_mandrill_inbound_emails_url: (*untyped) -> String
  def rails_mailgun_inbound_emails_url: (*untyped) -> String
  def rails_conductor_inbound_emails_url: (*untyped) -> String
  def new_rails_conductor_inbound_email_url: (*untyped) -> String
  def edit_rails_conductor_inbound_email_url: (*untyped) -> String
  def rails_conductor_inbound_email_url: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> String
  def rails_service_blob_url: (*untyped) -> String
  def rails_service_blob_proxy_url: (*untyped) -> String
  def rails_blob_representation_url: (*untyped) -> String
  def rails_blob_representation_proxy_url: (*untyped) -> String
  def rails_disk_service_url: (*untyped) -> String
  def update_rails_disk_service_url: (*untyped) -> String
  def rails_direct_uploads_url: (*untyped) -> String
  def rails_representation_url: (*untyped) -> String
  def rails_blob_url: (*untyped) -> String
  def rails_storage_proxy_url: (*untyped) -> String
  def rails_storage_redirect_url: (*untyped) -> String
end
